version = 0.1
[default.deploy.parameters]
stack_name = "ecommerce-adidas"
resolve_s3 = false
s3_bucket = "adidas-sam"
s3_prefix = "ecommerce-adidas"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
